server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # eureka server默认也是一个eureka client.以下两行仅将此App当成eureka server，不当成eureka client(由于是单机测试)
    register-with-eureka: false
    fetch-registry: false
    # 将eureka注册到哪个url
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #### 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false
