server:
  port: 9000

#security:
#  oauth2:
#    resource:
#      id: order-service
#      user-info-uri: http://localhost:8080/uaa/user
#      prefer-token-info: false

spring:
  application:
    name: consumer-movie-ribbon
  security:
    oauth2:
      registration:
        github:
          client-id: 5b63068d2d4f17851752
          client-secret: 5efd5d24fef403ff1d28b93725ecb34fd8263ccc
          client-name: Github user
          provider: github
          scope: user
          redirect-uri-template: http://oldinaction.xicp.net/github
          clientAuthenticationScheme: form
      provider:
        github:
          authorization-uri: https://github.com/login/oauth/authorize
          token-uri: https://github.com/login/oauth/access_token
      resource:
        userInfoUri: https://api.github.com/user
        preferTokenInfo: false
#      resource:
#        id: api-movie



# eureka客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://smalle:smalle@localhost:8761/eureka/
  instance:
    # 启用ip访问
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

# robbin负载均衡策略优先级：配置文件策略 > 代码级别策略 > ribbon默认策略(com.netflix.loadbalancer.ZoneAvoidanceRule)
provider-user:
  ribbon:
      # 当访问服务provider-user时采用随机策略RandomRule，此时访问其他服务时仍然为默认策略ZoneAvoidanceRule；WeightedResponseTimeRule响应时间加权策略
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 开启feign对hystrix的支持，默认是false
feign:
  hystrix:
    enabled: true
