server:
  port: 7010

spring:
  application:
    name: hystrix-turbine

# eureka客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://smalle:smalle@localhost:8761/eureka/
  instance:
    # 启用ip访问
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

turbine:
  # 配置Eureka中的serviceId列表，表明监控哪些服务
  appConfig: consumer-movie-ribbon,consumer-movie-ribbon2
  # 参数指定了集群名称为 default，当我们服务数量非常多的时候，可以启动多个 Turbine 服务来构建不同的聚合集群，而该参数可以用来区分这些不同的聚合集群，同时该参数值可以在 Hystrix 仪表盘中用来定位不同的聚合集群
#  clusterNameExpression: "'default'"
  # 匹配被监控节点eureka.instance.metadata-map.cluster的值中包含turbine.aggregator.clusterConfig的参数值
  clusterNameExpression: metadata['cluster']
  aggregator:
    # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster=<clusterConfig之一>访问
    # 当clusterNameExpression: default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default(多个使用逗号分隔)
#    clusterConfig: default
    clusterConfig: CUSTOMER1,CUSTOMER2


